import { buildInitialState } from "../src/state/seed.ts";
import { simulateSeasonQuick } from "../src/state/season.ts";

console.log("🔍 PHASE AAA-PERFORMANCE-1 — SIMULATION BOTTLENECK AUDIT\n");

const startTotal = Date.now();
let state = buildInitialState("0");
const buildTime = Date.now() - startTotal;

console.log(`Initial state build: ${buildTime}ms`);
console.log(`Clubs: ${Object.keys(state.clubs).length}`);
console.log(`Players: ${Object.keys(state.players).length}`);
console.log(`Leagues: ${new Set(Object.values(state.clubs).map((c) => c.leagueId)).size}\n`);

console.log(`═══════════════════════════════════════════════════════════`);
console.log(`RUNNING 1-SEASON BENCHMARK\n`);

// Measure season simulation
const seasonStart = Date.now();
state = simulateSeasonQuick(state);
const seasonTime = Date.now() - seasonStart;

console.log(`\n1-SEASON RUNTIME: ${seasonTime}ms`);
console.log(
  `Estimated 3-season runtime: ~${(seasonTime * 3).toLocaleString()}ms (${((seasonTime * 3) / 1000 / 60).toFixed(1)} min)`,
);
console.log(
  `Estimated 30-year runtime: ~${(seasonTime * 30).toLocaleString()}ms (${((seasonTime * 30) / 1000 / 60 / 60).toFixed(2)} hours)`,
);

console.log(`\n═══════════════════════════════════════════════════════════`);
console.log(`SYSTEM EVENT COUNTS (Season 1)\n`);

// Categorize all events
const eventTypes = new Map();
for (const event of state.events ?? []) {
  const count = (eventTypes.get(event.type) ?? 0) + 1;
  eventTypes.set(event.type, count);
}

const sortedEvents = [...eventTypes.entries()].sort((a, b) => b[1] - a[1]);
for (const [type, count] of sortedEvents) {
  console.log(`  ${String(type).padEnd(20)} : ${count.toString().padStart(6)}`);
}

const totalEvents = Array.from(eventTypes.values()).reduce((a, b) => a + b, 0);
console.log(`  ${"Total".padEnd(20)} : ${totalEvents.toString().padStart(6)}`);

console.log(`\n═══════════════════════════════════════════════════════════`);
console.log(`ECOSYSTEM STATE\n`);

const clubs = Object.values(state.clubs).length;
const players = Object.keys(state.players).length;
const retired = Object.values(state.players).filter((p: any) => p.status === "retired").length;
const active = players - retired;

console.log(`Clubs: ${clubs.toLocaleString()}`);
console.log(
  `Players: ${players.toLocaleString()} (${active.toLocaleString()} active, ${retired} retired)`,
);
console.log(`Players/club: ${(players / clubs).toFixed(1)}`);
console.log(`Match results: ${(state.matchResults ?? []).length}`);

console.log(`\n═══════════════════════════════════════════════════════════`);
console.log(`PERFORMANCE ANALYSIS\n`);

console.log(`Bottleneck Indicators:`);
console.log(`  - 1 season takes ${seasonTime}ms for ${clubs} clubs`);
console.log(`  - That's ~${(seasonTime / clubs).toFixed(1)}ms per club`);
console.log(`  - Event creation rate: ${(totalEvents / (seasonTime / 1000)).toFixed(0)}/second`);

// Check for expensive patterns
console.log(`\nExpensive Operation Counts:`);

// Count matches (main bottleneck suspect)
const matchCount = state.matchResults?.length ?? 0;
const msPerMatch = seasonTime / (matchCount || 1);
console.log(`  Matches: ${matchCount} (${msPerMatch.toFixed(1)}ms each)`);

// Count transfers and youth (should be generated by events)
const transferEvents = eventTypes.get("TRANSFER_COMPLETED") ?? 0;
const youthEvents = eventTypes.get("YOUTH_GENERATED") ?? 0;
const retireEvents = eventTypes.get("PLAYER_RETIRED") ?? 0;
console.log(`  Transfers: ${transferEvents}`);
console.log(`  Retirements: ${retireEvents}`);
console.log(`  Youth generation: ${youthEvents}`);

console.log(`\n═══════════════════════════════════════════════════════════`);
console.log(`ESTIMATED BOTTLENECKS\n`);

const MATCHES_PERCENTAGE = 0.6; // Matches are typically 60% of simulation time
const EVENTS_PERCENTAGE = 0.15; // Event processing 15%
const STATE_PERCENTAGE = 0.15; // State updates 15%
const OTHER_PERCENTAGE = 0.1; // Other systems 10%

console.log(`Estimated time allocation:`);
console.log(
  `  Match simulation (${(MATCHES_PERCENTAGE * 100).toFixed(0)}%): ~${(seasonTime * MATCHES_PERCENTAGE).toFixed(0)}ms`,
);
console.log(
  `  Event processing (${(EVENTS_PERCENTAGE * 100).toFixed(0)}%): ~${(seasonTime * EVENTS_PERCENTAGE).toFixed(0)}ms`,
);
console.log(
  `  State mutations (${(STATE_PERCENTAGE * 100).toFixed(0)}%): ~${(seasonTime * STATE_PERCENTAGE).toFixed(0)}ms`,
);
console.log(
  `  Other systems (${(OTHER_PERCENTAGE * 100).toFixed(0)}%): ~${(seasonTime * OTHER_PERCENTAGE).toFixed(0)}ms`,
);

console.log(`\n═══════════════════════════════════════════════════════════`);
console.log(`SAFE OPTIMIZATION OPPORTUNITIES\n`);

console.log(`High Priority (likely big wins):`);
console.log(`  1. Match simulation caching/batching`);
console.log(`  2. Reduce fixture generation frequency`);
console.log(`  3. Lazy fixture scheduling`);
console.log(`\nMedium Priority (moderate gains):`);
console.log(`  1. Batch player development updates`);
console.log(`  2. Consolidate transfer window operations`);
console.log(`  3. Cache player ratings calculations`);
console.log(`\nLow Priority (small gains):`);
console.log(`  1. Event object pooling`);
console.log(`  2. Reduce state cloning`);
console.log(`  3. Memoize recurring lookups`);

console.log(`\n═══════════════════════════════════════════════════════════`);
console.log(`RISK ASSESSMENT\n`);

console.log(`Most risky to change:`);
console.log(`  ❌ Match simulation algorithm`);
console.log(`  ❌ Promotion/relegation logic`);
console.log(`  ❌ Transfer window mechanics`);
console.log(`  ❌ Player retirement calculation`);
console.log(`\nSafer to optimize:`);
console.log(`  ✓ Fixture scheduling frequency`);
console.log(`  ✓ Event batching`);
console.log(`  ✓ State update coalescing`);
console.log(`  ✓ Caching/memoization`);

console.log(`\n═══════════════════════════════════════════════════════════`);
console.log(`\n✅ AUDIT COMPLETE — Analysis ready for optimization phase\n`);

process.exit(0);
