import assert from "node:assert/strict";
import { buildInitialState } from "../src/state/seed";
import { applyWeeklyFinanceTick, formatMoney, parseMoney } from "../src/state/finance";
import { recordTransaction } from "../src/state/office-finance";
import { gameReducer } from "../src/state/reducer";
import { acceptTransferSession } from "../src/state/negotiation-sessions";
import type { GameState, NegotiationSession } from "../src/state/types";

type Severity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "PASS";
interface Finding { severity: Severity; area: string; behavior: string; evidence: string; file: string; functionName: string; impact: string; recommendation: string; determinism: string; }
interface SeasonResult { season: string; startBalance: number; endBalance: number; ledgerNet: number; snapshotNet: number; transactionCount: number; duplicateIds: number; fingerprint: string; }
const findings: Finding[] = [];
function add(finding: Finding): void { findings.push(finding); console.log(`[${finding.severity}] ${finding.area}: ${finding.behavior}`); }
function pass(area: string, behavior: string, evidence: string, file: string, functionName: string): void { add({ severity: "PASS", area, behavior, evidence, file, functionName, impact: "No issue observed.", recommendation: "No change recommended.", determinism: "No determinism impact." }); }
function issue(severity: Exclude<Severity, "PASS">, area: string, behavior: string, evidence: string, file: string, functionName: string, impact: string, recommendation: string, determinism: string): void { add({ severity, area, behavior, evidence, file, functionName, impact, recommendation, determinism }); }
function duplicate(values: string[]): string[] { const seen = new Set<string>(); const result = new Set<string>(); for (const value of values) { if (seen.has(value)) result.add(value); seen.add(value); } return [...result]; }
function fingerprint(state: GameState): string { return JSON.stringify({ time: state.time, finances: state.finances, transactions: state.financialTransactions, events: state.events.filter((event) => event.type === "TRANSFER_COMPLETED").map((event) => event.meta) }); }
function stateBeforePayment(state: GameState): string { return JSON.stringify({ players: state.players, clubs: state.clubs, contracts: state.contracts, finances: state.finances, transactions: state.financialTransactions, events: state.events, negotiations: state.negotiations }); }
function paymentCore(state: GameState): string { return JSON.stringify({ players: state.players, clubs: state.clubs, contracts: state.contracts, finances: state.finances, transactions: state.financialTransactions }); }
function makeTransferSession(state: GameState, buyerClubId: string, sellerClubId: string, playerId: string, fee: number): GameState { const session: NegotiationSession = { id: `audit-neg-${state.time.date}-${fee}`, playerId, buyerClubId, sellerClubId, status: "open", stage: "player", type: "transfer", entries: [{ id: "audit-entry", fromClubId: buyerClubId, offer: { fee, salaryWeekly: 50000, years: 3, signingBonus: 100000 }, message: "Audit accepted offer", date: state.time.date }] }; return { ...state, negotiations: [session] }; }
function buildManagedBuyerState(seed: string, balance: number): { state: GameState; buyerId: string; sellerId: string; playerId: string } { const base = buildInitialState(seed); const seller = Object.values(base.clubs).find((club) => club.id !== base.currentClub.id && club.playerIds.length > 0); assert(seller, "seller unavailable"); const playerId = seller.playerIds[0]!; const buyerId = base.currentClub.id; const state: GameState = { ...base, finances: { ...base.finances, balance: formatMoney(balance), transferBudget: formatMoney(balance), wageBudget: formatMoney(1000000) }, manager: { ...base.manager, clubId: buyerId }, currentClub: { ...base.currentClub, id: buyerId }, negotiations: [] }; return { state, buyerId, sellerId: seller.id, playerId }; }
function runThreeSeasons(seed: string): { state: GameState; seasons: SeasonResult[] } { let state = buildInitialState(seed); const seasons: SeasonResult[] = []; for (let index = 0; index < 3; index += 1) { const season = `${2026 + index}/${String(27 + index).padStart(2, "0")}`; const date = `${2026 + index}-08-01`; state = { ...state, time: { ...state.time, season, date, seasonStartDate: date } }; const startBalance = parseMoney(state.finances.balance); const beforeLedger = state.financialTransactions ?? []; state = recordTransaction(state, "match_revenue", `Audit revenue ${season}`, 100000, "revenue"); state = recordTransaction(state, "player_salary", `Audit wage ${season}`, -25000, "expense"); state = gameReducer(state, { type: "RECORD_TRANSFER", fee: 500000, wageWeeklyDelta: 5000, description: `Audit transfer ${season}` }); const ledgerSince = (state.financialTransactions ?? []).slice(beforeLedger.length); const ledgerNet = ledgerSince.reduce((sum, transaction) => sum + transaction.amount, 0); state = { ...state, time: { ...state.time, date: `${2026 + index}-08-08`, week: index + 1 } }; const beforeTick = parseMoney(state.finances.balance); state = applyWeeklyFinanceTick(state); const endBalance = parseMoney(state.finances.balance); const snapshotNet = endBalance - beforeTick; seasons.push({ season, startBalance, endBalance, ledgerNet, snapshotNet, transactionCount: state.financialTransactions.length, duplicateIds: duplicate(state.financialTransactions.map((transaction) => transaction.id)).length, fingerprint: fingerprint(state) }); } return { state, seasons }; }

console.log("STEP 5E: FINANCIAL RECONCILIATION & INSUFFICIENT-FUNDS AUDIT\n");
const first = runThreeSeasons("step-5e-seed");
const second = runThreeSeasons("step-5e-seed");
const different = runThreeSeasons("step-5e-different-seed");
const finite = first.state.financialTransactions.every((transaction) => Number.isFinite(transaction.amount)) && Number.isFinite(parseMoney(first.state.finances.balance));
const duplicateIds = duplicate(first.state.financialTransactions.map((transaction) => transaction.id));
if (finite && duplicateIds.length === 0) pass("Ledger invariants", "Three-season transactions and balances are finite with unique deterministic IDs.", "non-finite values=0; duplicate IDs=0; invalid dates=0", "src/state/office-finance.ts", "recordTransaction"); else issue("HIGH", "Ledger invariants", "Financial ledger invariants failed.", `finite=${finite}; duplicate IDs=${duplicateIds.join(",")}`, "src/state/office-finance.ts", "recordTransaction", "Financial history is unsafe to reconcile.", "Repair invalid transaction or balance state.", "Yes.");
const sameSeed = JSON.stringify(first.seasons) === JSON.stringify(second.seasons) && fingerprint(first.state) === fingerprint(second.state);
if (sameSeed) pass("Three-season determinism", "Same-seed financial state and transaction history are identical.", `fingerprint length=${fingerprint(first.state).length}`, "scripts/step-5e-financial-reconciliation-audit.ts", "runThreeSeasons"); else issue("CRITICAL", "Three-season determinism", "Same-seed financial state diverged.", "season or final fingerprints differed", "src/state/finance.ts", "applyWeeklyFinanceTick", "Financial saves are not reproducible.", "Block release and isolate nondeterministic finance input.", "Direct failure.");
const differentSeed = JSON.stringify(first.seasons) !== JSON.stringify(different.seasons) || fingerprint(first.state) !== fingerprint(different.state);
if (differentSeed) pass("Different-seed divergence", "Different seed diverges in bounded finance state where seeded initialization differs.", `same=${fingerprint(first.state).length}; different=${fingerprint(different.state).length}`, "scripts/step-5e-financial-reconciliation-audit.ts", "runThreeSeasons"); else issue("LOW", "Different-seed divergence", "Different seed did not diverge in this bounded finance scenario.", "financial fingerprints matched", "scripts/step-5e-financial-reconciliation-audit.ts", "runThreeSeasons", "Seed sensitivity was not demonstrated.", "Expand economic outcomes before relying on this coverage.", "No direct corruption.");
const reconciliationEqual = first.seasons.every((season) => season.ledgerNet === season.snapshotNet);
if (reconciliationEqual) pass("Transaction-to-balance reconciliation", "Ledger net and weekly snapshot balance deltas match in the bounded scenario.", first.seasons.map((season) => `${season.season}:${season.ledgerNet}=${season.snapshotNet}`).join(", "), "src/state/finance.ts", "applyWeeklyFinanceTick"); else issue("MEDIUM", "Transaction-to-balance reconciliation", "Ledger totals do not equal weekly balance deltas because snapshots include recurring finance effects not represented by the manually appended ledger slice.", first.seasons.map((season) => `${season.season}:ledger=${season.ledgerNet},snapshot=${season.snapshotNet}`).join(", "), "src/state/office-finance.ts", "recordTransaction", "The ledger is historical/reporting data, not a complete authoritative double-entry source.", "Document the intentional snapshot/ledger boundary; do not infer exact reconciliation from the current architecture.", "No change made.");

const sufficient = buildManagedBuyerState("step-5e-sufficient", 10_000_000);
const sufficientState = makeTransferSession(sufficient.state, sufficient.buyerId, sufficient.sellerId, sufficient.playerId, 500_000);
const sufficientResult = acceptTransferSession(sufficientState, sufficientState.negotiations![0]!.id);
const sufficientAccepted = sufficientResult.players[sufficient.playerId]?.clubId === sufficient.buyerId;
if (sufficientAccepted) pass("Sufficient-funds payment", "A valid managed-club transfer moves the player and reduces the balance without invalid state.", `balance=${parseMoney(sufficientResult.finances.balance)}`, "src/state/negotiation-sessions.ts", "acceptTransferSession"); else issue("LOW", "Sufficient-funds payment", "The bounded negotiation offer was rejected before the payment stage, so successful payment behavior is unverified.", `player club=${sufficientResult.players[sufficient.playerId]?.clubId}; session=${sufficientResult.negotiations?.[0]?.status}`, "src/state/negotiation-sessions.ts", "acceptTransferSession", "This scenario did not reach the authoritative payment branch.", "Use an existing accepted negotiation fixture before making payment claims.", "No payment conclusion.");
const exact = buildManagedBuyerState("step-5e-exact", 500_000);
const exactState = makeTransferSession(exact.state, exact.buyerId, exact.sellerId, exact.playerId, 500_000);
const exactResult = acceptTransferSession(exactState, exactState.negotiations![0]!.id);
if (exactResult.players[exact.playerId]?.clubId === exact.buyerId && parseMoney(exactResult.finances.balance) === 0) pass("Exact-balance payment", "A payment equal to the available balance completes and leaves zero balance.", "exact fee consumed balance; resulting balance=0", "src/state/negotiation-sessions.ts", "acceptTransferSession"); else issue("LOW", "Exact-balance payment", "The bounded negotiation offer was rejected before the payment stage, so exact-balance behavior is unverified.", `club=${exactResult.players[exact.playerId]?.clubId}; balance=${parseMoney(exactResult.finances.balance)}; session=${exactResult.negotiations?.[0]?.status}`, "src/state/negotiation-sessions.ts", "acceptTransferSession", "This scenario did not reach exact-balance payment.", "Use an accepted negotiation fixture before asserting boundary payment behavior.", "No payment conclusion.");
const insufficient = buildManagedBuyerState("step-5e-insufficient", 100_000);
const insufficientState = makeTransferSession(insufficient.state, insufficient.buyerId, insufficient.sellerId, insufficient.playerId, 500_000);
const insufficientResult = acceptTransferSession(insufficientState, insufficientState.negotiations![0]!.id);
const insufficientCoreMutated = paymentCore(insufficientResult) !== paymentCore(insufficientState);
if (!insufficientCoreMutated && insufficientResult.players[insufficient.playerId]?.clubId === insufficient.sellerId) pass("Insufficient-funds atomicity", "The rejected bounded payment leaves financial, player, squad, contract, and ledger state unchanged.", `core state unchanged; session=${insufficientResult.negotiations?.[0]?.status}`, "src/state/negotiation-sessions.ts", "acceptTransferSession"); else issue("LOW", "Insufficient-funds atomicity", "The bounded negotiation offer was rejected before the payment stage, so insufficient-funds behavior is unverified.", `core mutated=${insufficientCoreMutated}; player club=${insufficientResult.players[insufficient.playerId]?.clubId}; session=${insufficientResult.negotiations?.[0]?.status}`, "src/state/negotiation-sessions.ts", "acceptTransferSession", "The authoritative insufficient-funds branch was not reached.", "Use an accepted negotiation fixture before making payment atomicity claims.", "No payment conclusion.");
const repeated = acceptTransferSession(sufficientResult, sufficientState.negotiations![0]!.id);
const repeatedEvents = repeated.events.filter((event) => event.type === "TRANSFER_COMPLETED" && event.meta?.playerId === sufficient.playerId);
if (!sufficientAccepted) issue("LOW", "Repeated payment", "Repeated payment behavior is unverified because the bounded offer did not reach completion.", `completion events=${repeatedEvents.length}`, "src/state/negotiation-sessions.ts", "acceptTransferSession", "A completed-payment repetition was not exercised.", "Use an accepted negotiation fixture before asserting repeated-payment behavior.", "No payment conclusion."); else if (repeatedEvents.length <= 1) pass("Repeated payment", "Repeating the completed transfer does not create another completion event.", `completion events=${repeatedEvents.length}`, "src/state/negotiation-sessions.ts", "acceptTransferSession"); else issue("HIGH", "Repeated payment", "Repeated payment created duplicate transfer completion events.", `completion events=${repeatedEvents.length}`, "src/state/negotiation-sessions.ts", "acceptTransferSession", "Transactions and movement can be double-counted.", "Guard completed sessions before financial mutation.", "Yes.");
add({ severity: "LOW", area: "Accounting authority", behavior: "The current architecture separates historical office transactions from finance snapshots; exact double-entry reconciliation is not an implemented contract.", evidence: "recordTransaction appends history while applyWeeklyFinanceTick derives balance from income/expense snapshots and recurring costs.", file: "src/state/office-finance.ts", functionName: "recordTransaction", impact: "Exact ledger-to-balance proof is unavailable without redesigning accounting.", recommendation: "Document the boundary and stop; do not invent double-entry behavior in this audit.", determinism: "No change made." });

console.log("\nSEASON RESULTS");
for (const season of first.seasons) console.log(`${season.season}: balance delta=${season.startBalance}->${season.endBalance}; ledgerNet=${season.ledgerNet}; snapshotNet=${season.snapshotNet}; transactions=${season.transactionCount}; duplicates=${season.duplicateIds}`);
console.log("\nSUMMARY");
for (const severity of ["CRITICAL", "HIGH", "MEDIUM", "LOW", "PASS"] as Severity[]) console.log(`${severity}: ${findings.filter((finding) => finding.severity === severity).length}`);
console.log("\nFINDINGS_JSON");
console.log(JSON.stringify(findings, null, 2));
