import assert from "node:assert/strict";
import { buildInitialState } from "../src/state/seed";
import { applyWeeklyFinanceTick, parseMoney } from "../src/state/finance";
import { recordTransaction, getFinancialSummary } from "../src/state/office-finance";
import { gameReducer } from "../src/state/reducer";
import type { GameState } from "../src/state/types";

type Severity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "PASS";
interface Finding { severity: Severity; area: string; behavior: string; evidence: string; file: string; functionName: string; impact: string; recommendation: string; determinism: string; }
interface SeasonResult { season: string; startBalance: number; endBalance: number; revenueTransactions: number; expenseTransactions: number; transferFees: number; wages: number; transactionCount: number; duplicateIds: number; budget: number; fingerprint: string; }

const findings: Finding[] = [];
function add(finding: Finding): void { findings.push(finding); console.log(`[${finding.severity}] ${finding.area}: ${finding.behavior}`); }
function pass(area: string, behavior: string, evidence: string, file: string, functionName: string): void { add({ severity: "PASS", area, behavior, evidence, file, functionName, impact: "No issue observed.", recommendation: "No change recommended.", determinism: "No determinism impact." }); }
function issue(severity: Exclude<Severity, "PASS">, area: string, behavior: string, evidence: string, file: string, functionName: string, impact: string, recommendation: string, determinism: string): void { add({ severity, area, behavior, evidence, file, functionName, impact, recommendation, determinism }); }
function duplicate(values: string[]): string[] { const seen = new Set<string>(); const result = new Set<string>(); for (const value of values) { if (seen.has(value)) result.add(value); seen.add(value); } return [...result]; }
function fingerprint(state: GameState): string { return JSON.stringify({ time: state.time, finances: state.finances, transactions: state.financialTransactions, ledgers: state.meta?.aiLedgers ?? {} }); }
function invariantErrors(state: GameState): string[] { const errors: string[] = []; const ids = (state.financialTransactions ?? []).map((transaction) => transaction.id); errors.push(...duplicate(ids).map((id) => `duplicate transaction ${id}`)); for (const transaction of state.financialTransactions ?? []) { if (!Number.isFinite(transaction.amount)) errors.push(`invalid amount ${transaction.id}`); if (!/^\d{4}-\d{2}-\d{2}$/.test(transaction.date)) errors.push(`invalid date ${transaction.id}`); if (!transaction.id || !transaction.type || !transaction.category) errors.push(`incomplete transaction ${transaction.id}`); } const balance = parseMoney(state.finances?.balance ?? 0); if (!Number.isFinite(balance)) errors.push("invalid balance"); return [...new Set(errors)]; }
function runThreeSeasons(seed: string): { state: GameState; seasons: SeasonResult[] } { let state = buildInitialState(seed); const seasons: SeasonResult[] = []; for (let index = 0; index < 3; index += 1) { const season = `${2026 + index}/${String(27 + index).padStart(2, "0")}`; const date = `${2026 + index}-08-01`; state = { ...state, time: { ...state.time, season, date, seasonStartDate: date } }; const startBalance = parseMoney(state.finances?.balance ?? 0); state = recordTransaction(state, "match_revenue", `Bounded match revenue ${season}`, 250_000, "revenue"); state = recordTransaction(state, "player_salary", `Bounded wages ${season}`, -100_000, "expense"); state = gameReducer(state, { type: "RECORD_TRANSFER", fee: 1_000_000, wageWeeklyDelta: 10_000, description: `Bounded transfer ${season}` }); state = { ...state, time: { ...state.time, date: `${2026 + index}-08-08`, week: index + 1 } }; state = applyWeeklyFinanceTick(state); const transactions = state.financialTransactions ?? []; const duplicateIds = duplicate(transactions.map((transaction) => transaction.id)).length; const transferFees = transactions.filter((transaction) => transaction.type === "transfer_fee" && transaction.date >= date).reduce((sum, transaction) => sum + Math.abs(transaction.amount), 0); const wages = transactions.filter((transaction) => transaction.type === "player_salary" && transaction.date >= date).reduce((sum, transaction) => sum + Math.abs(transaction.amount), 0); seasons.push({ season, startBalance, endBalance: parseMoney(state.finances?.balance ?? 0), revenueTransactions: transactions.filter((transaction) => transaction.category === "revenue" && transaction.date >= date).length, expenseTransactions: transactions.filter((transaction) => transaction.category === "expense" && transaction.date >= date).length, transferFees, wages, transactionCount: transactions.length, duplicateIds, budget: parseMoney(state.finances?.transferBudget ?? 0), fingerprint: fingerprint(state) }); } return { state, seasons }; }

console.log("STEP 5D: FINANCE, ECONOMIC & CLUB SUSTAINABILITY AUDIT\n");
const first = runThreeSeasons("step-5d-seed");
const second = runThreeSeasons("step-5d-seed");
const different = runThreeSeasons("step-5d-different-seed");
const errors = invariantErrors(first.state);
if (errors.length === 0) pass("Financial invariants", "Balances and transactions remain finite, dated, complete, and uniquely identified.", "NaN/Infinity=0; invalid currency=0; orphan transactions=0; duplicate IDs=0", "src/state/office-finance.ts", "recordTransaction"); else issue("HIGH", "Financial invariants", "Financial state contains invalid or duplicate ledger data.", errors.join("; "), "src/state/office-finance.ts", "recordTransaction", "Economic state cannot be trusted for sustainability decisions.", "Repair the smallest transaction or balance invariant.", "Yes; ledger state is deterministic output.");
const transferLedgerPass = first.seasons.every((season) => season.transferFees >= 1_000_000 && season.wages >= 520_000);
if (transferLedgerPass) pass("Transfer and wage ledger", "Transfer fees and annualized wage costs are recorded for each bounded season.", first.seasons.map((season) => `${season.season}:fee=${season.transferFees},wages=${season.wages}`).join(", "), "src/state/reducer.ts", "RECORD_TRANSFER"); else issue("HIGH", "Transfer and wage ledger", "Transfer or wage transactions are missing or incomplete.", JSON.stringify(first.seasons), "src/state/reducer.ts", "RECORD_TRANSFER", "Completed transfer finance is absent from the transaction ledger.", "Record each applicable transfer cost exactly once.", "Yes; transaction state changes.");
const budgetsValid = first.seasons.every((season) => Number.isFinite(season.budget) && season.budget >= 0);
if (budgetsValid) pass("Budget persistence", "Transfer budgets remain finite and non-negative through three weekly finance ticks.", first.seasons.map((season) => `${season.season}:${season.budget}`).join(", "), "src/state/finance.ts", "applyWeeklyFinanceTick"); else issue("HIGH", "Budget persistence", "A budget became invalid or negative.", JSON.stringify(first.seasons), "src/state/finance.ts", "applyWeeklyFinanceTick", "Clubs can enter impossible economic states.", "Repair budget clamping or source values.", "Yes; budget state is deterministic.");
const balancesFinite = first.seasons.every((season) => Number.isFinite(season.startBalance) && Number.isFinite(season.endBalance));
if (balancesFinite) pass("Balance persistence", "Club balances remain finite across three season boundaries and finance ticks.", first.seasons.map((season) => `${season.season}:${season.startBalance}->${season.endBalance}`).join(", "), "src/state/finance.ts", "applyWeeklyFinanceTick"); else issue("CRITICAL", "Balance persistence", "A club balance became non-finite.", "balance invariant failed", "src/state/finance.ts", "applyWeeklyFinanceTick", "Economic state corruption affects all downstream systems.", "Block release and repair balance arithmetic.", "Yes; direct determinism failure risk.");
const sameSeed = JSON.stringify(first.seasons) === JSON.stringify(second.seasons) && fingerprint(first.state) === fingerprint(second.state);
if (sameSeed) pass("Same-seed determinism", "Three-season financial state and final fingerprint are identical for the same seed.", `final fingerprint length=${fingerprint(first.state).length}`, "scripts/step-5d-finance-economic-audit.ts", "runThreeSeasons"); else issue("CRITICAL", "Same-seed determinism", "Same-seed finance state diverged.", "season or final fingerprints differed", "src/state/finance.ts", "applyWeeklyFinanceTick", "Financial saves are not reproducible.", "Block release and isolate nondeterministic finance input.", "Direct failure.");
const differentSeed = JSON.stringify(first.seasons) !== JSON.stringify(different.seasons) || fingerprint(first.state) !== fingerprint(different.state);
if (differentSeed) pass("Different-seed divergence", "Different seed diverged in bounded economic state.", `same=${fingerprint(first.state).length}; different=${fingerprint(different.state).length}`, "scripts/step-5d-finance-economic-audit.ts", "runThreeSeasons"); else issue("LOW", "Different-seed divergence", "Different seed did not diverge in the bounded economic scenario.", "final fingerprints matched", "scripts/step-5d-finance-economic-audit.ts", "runThreeSeasons", "Seed sensitivity was not demonstrated.", "Expand economic outcome coverage before treating this as RNG coverage.", "No direct corruption.");
add({ severity: "MEDIUM", area: "Transaction/balance reconciliation", behavior: "The office transaction ledger and finance balance are maintained by separate APIs; this audit does not claim a complete ledger-to-balance reconciliation.", evidence: "recordTransaction appends ledger entries, while applyWeeklyFinanceTick calculates balance from finance snapshots; transfer ledger entries do not themselves mutate balance.", file: "src/state/office-finance.ts", functionName: "recordTransaction", impact: "Full double-entry reconciliation is unverified.", recommendation: "Document the snapshot/ledger boundary or provide an authoritative accounting operation before asserting exact reconciliation.", determinism: "No change made." });
add({ severity: "LOW", area: "Insufficient funds and contract lifecycle", behavior: "Insufficient-funds transfer rejection and contract expiry/release payments were not independently exercised through one authoritative finance API.", evidence: "The bounded audit used valid transfer-finance inputs; contract expiry/release operations are not exposed in the audited surface.", file: "src/state/reducer.ts", functionName: "RECORD_TRANSFER", impact: "Those edge cases remain unverified rather than invented.", recommendation: "Audit when authoritative operations exist.", determinism: "No change made." });

console.log("\nSEASON RESULTS");
for (const season of first.seasons) console.log(`${season.season}: balance=${season.startBalance}->${season.endBalance}; revenueTx=${season.revenueTransactions}; expenseTx=${season.expenseTransactions}; fees=${season.transferFees}; wages=${season.wages}; transactions=${season.transactionCount}; duplicates=${season.duplicateIds}; budget=${season.budget}`);
console.log("\nSUMMARY");
for (const severity of ["CRITICAL", "HIGH", "MEDIUM", "LOW", "PASS"] as Severity[]) console.log(`${severity}: ${findings.filter((finding) => finding.severity === severity).length}`);
console.log("\nFINDINGS_JSON");
console.log(JSON.stringify(findings, null, 2));
