import assert from "node:assert/strict";
import { buildInitialState } from "../src/state/seed";
import { planAiWorldWork, runAiWorldScheduler } from "../src/state/ai-world-scheduler";
import { runAiActions } from "../src/state/ai-actions";
import { generateReplacementManager } from "../src/state/ai-evolution";
import { evaluateJobSecurity, generateJobOffers, acceptJob } from "../src/state/jobs";
import { buildClubDecisionContext, evaluateClubPriorities, recommendTrainingDecision } from "../src/state/ai-decisions";
import type { GameState } from "../src/state/types";

type Severity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "PASS";
interface Finding { severity: Severity; area: string; behavior: string; evidence: string; file: string; functionName: string; impact: string; recommendation: string; determinism: string; }
interface SeasonResult { season: string; scheduledDays: number; processedClubs: number; managers: number; negotiations: number; transfers: number; invalid: number; fingerprint: string; }
const findings: Finding[] = [];
function add(finding: Finding): void { findings.push(finding); console.log(`[${finding.severity}] ${finding.area}: ${finding.behavior}`); }
function pass(area: string, behavior: string, evidence: string, file: string, functionName: string): void { add({ severity: "PASS", area, behavior, evidence, file, functionName, impact: "No issue observed.", recommendation: "No change recommended.", determinism: "No determinism impact." }); }
function issue(severity: Exclude<Severity, "PASS">, area: string, behavior: string, evidence: string, file: string, functionName: string, impact: string, recommendation: string, determinism: string): void { add({ severity, area, behavior, evidence, file, functionName, impact, recommendation, determinism }); }
function duplicate(values: string[]): string[] { const seen = new Set<string>(); const result = new Set<string>(); for (const value of values) { if (seen.has(value)) result.add(value); seen.add(value); } return [...result]; }
function fingerprint(state: GameState): string { return JSON.stringify({ time: state.time, clubs: Object.fromEntries(Object.entries(state.clubs).sort()), players: Object.fromEntries(Object.entries(state.players).sort()), ledgers: state.meta?.aiLedgers ?? {}, scheduler: state.meta?.aiScheduler ?? {}, negotiations: state.negotiations, transfers: state.transfers, events: state.events.map((event) => ({ id: event.id, date: event.date, type: event.type, meta: event.meta })) }); }
function invalidState(state: GameState): string[] { const errors: string[] = []; const activePlayers = new Set<string>(); for (const [clubId, club] of Object.entries(state.clubs)) { if (club.aiManager && !club.aiManager.id) errors.push(`manager missing id ${clubId}`); for (const playerId of club.playerIds) { if (!state.players[playerId]) errors.push(`invalid player ref ${clubId}:${playerId}`); if (activePlayers.has(playerId)) errors.push(`player in multiple squads ${playerId}`); activePlayers.add(playerId); } } for (const player of Object.values(state.players)) if (player.clubId && !state.clubs[player.clubId]) errors.push(`invalid club pointer ${player.id}`); const eventIds = state.events.map((event) => event.id); errors.push(...duplicate(eventIds).map((id) => `duplicate event ${id}`)); const managers = Object.values(state.clubs).filter((club) => club.aiManager).map((club) => club.aiManager!.id); errors.push(...duplicate(managers).map((id) => `duplicate manager ${id}`)); return [...new Set(errors)]; }
function compact(seed: string): GameState { const base = buildInitialState(seed); const selected = Object.values(base.clubs).slice(0, 6); const selectedIds = new Set(selected.map((club) => club.id)); const players = Object.fromEntries(Object.values(base.players).filter((player) => player.clubId && selectedIds.has(player.clubId)).map((player) => [player.id, player])); const clubs = Object.fromEntries(selected.map((club) => [club.id, { ...club, playerIds: club.playerIds.filter((id) => Boolean(players[id])) }])); return { ...base, clubs, players, currentClub: clubs[base.currentClub.id] ?? selected[0]!, manager: { ...base.manager, clubId: (clubs[base.currentClub.id] ?? selected[0]!).id }, fixtures: [], negotiations: [], transfers: [], events: [], news: [], time: { ...base.time, date: "2026-08-01", season: "2026/27", seasonStartDate: "2026-08-01", day: 1, week: 1 }, gameSeed: seed }; }
function fullWorldCoverage(): { aiClubs: number; covered: number; days: number; maxDaily: number; maxPlan: number } { const state = buildInitialState("step-6a-coverage"); const aiClubs = Object.values(state.clubs).filter((club) => club.aiManager).map((club) => club.id); const covered = new Set<string>(); let date = state.time.date; let lastPeriodic: string | undefined; const days = 12000; let maxDaily = 0; for (let index = 0; index < days; index += 1) { const planState: GameState = { ...state, time: { ...state.time, date, day: index + 1 }, meta: { ...(state.meta ?? {}), aiScheduler: { lastPeriodicReviewDate: lastPeriodic } } }; const plan = planAiWorldWork(planState); maxDaily = Math.max(maxDaily, plan.items.length); for (const item of plan.items) covered.add(item.clubId); if (plan.items.some((item) => item.reasons.includes("periodic-review"))) lastPeriodic = date; date = new Date(`${date}T00:00:00Z`).toISOString().slice(0, 10); const next = new Date(`${date}T00:00:00Z`); next.setUTCDate(next.getUTCDate() + 1); date = next.toISOString().slice(0, 10); } return { aiClubs: aiClubs.length, covered: aiClubs.filter((id) => covered.has(id)).length, days, maxDaily, maxPlan: 4 }; }
function runSeasons(seed: string): { state: GameState; seasons: SeasonResult[] } { let state = compact(seed); const seasons: SeasonResult[] = []; for (let seasonIndex = 0; seasonIndex < 3; seasonIndex += 1) { const season = `${2026 + seasonIndex}/${String(27 + seasonIndex).padStart(2, "0")}`; let processed = new Set<string>(); let date = `${2026 + seasonIndex}-08-01`; for (let day = 0; day < 90; day += 1) { state = { ...state, time: { ...state.time, season, date, day: seasonIndex * 90 + day + 1, week: Math.floor(day / 7) + 1 } }; const plan = planAiWorldWork(state); for (const item of plan.items) processed.add(item.clubId); state = runAiWorldScheduler(state); date = new Date(`${date}T00:00:00Z`).toISOString().slice(0, 10); const next = new Date(`${date}T00:00:00Z`); next.setUTCDate(next.getUTCDate() + 1); date = next.toISOString().slice(0, 10); } const managerCount = Object.values(state.clubs).filter((club) => club.aiManager).length; seasons.push({ season, scheduledDays: 90, processedClubs: processed.size, managers: managerCount, negotiations: state.negotiations.length, transfers: state.events.filter((event) => event.type === "TRANSFER_COMPLETED").length, invalid: invalidState(state).length, fingerprint: fingerprint(state) }); } return { state, seasons }; }

console.log("STEP 6A: AI WORLD & MANAGER ECOSYSTEM AUDIT\n");
const coverage = fullWorldCoverage();
if (coverage.covered === coverage.aiClubs && coverage.maxDaily <= coverage.maxPlan) pass("Scheduler population coverage", "Periodic scheduling eventually covers every AI club without exceeding the daily cap.", `AI clubs=${coverage.aiClubs}; covered=${coverage.covered}; window=${coverage.days} days; max daily=${coverage.maxDaily}`, "src/state/ai-world-scheduler.ts", "planAiWorldWork"); else issue("HIGH", "Scheduler population coverage", "Some AI clubs were not covered by periodic scheduling in the measurement window or the daily cap was exceeded.", `AI clubs=${coverage.aiClubs}; covered=${coverage.covered}; max daily=${coverage.maxDaily}`, "src/state/ai-world-scheduler.ts", "periodicBatch", "AI clubs can be systematically starved.", "Measure a longer window or repair rotation only with proof of persistent starvation.", "Changing scheduling would affect deterministic AI state.");
const first = runSeasons("step-6a-seed");
const second = runSeasons("step-6a-seed");
const different = runSeasons("step-6a-different-seed");
const errors = invalidState(first.state);
if (errors.length === 0) pass("AI state integrity", "Bounded AI actions preserve manager, player, club, squad, event, and manager-identity invariants.", "invalid refs=0; duplicate managers=0; duplicate events=0; squad conflicts=0", "src/state/ai-actions.ts", "runAiActions"); else issue("HIGH", "AI state integrity", "AI actions produced invalid state references or duplicated identity/events.", errors.join("; "), "src/state/ai-actions.ts", "runAiActions", "AI decisions can corrupt shared world state.", "Repair the smallest failing state transition.", "Yes; AI state is deterministic output.");
const decisionChecks = Object.values(first.state.clubs).filter((club) => club.aiManager).map((club) => { const context = buildClubDecisionContext(first.state, club.id); const priorities = evaluateClubPriorities(context, { randomness: 3, seedSalt: first.state.time.date }); const training = recommendTrainingDecision(first.state, club.id); return Boolean(context && priorities.topPriority && training.focus && training.intensity); });
if (decisionChecks.every(Boolean)) pass("AI decision integrity", "AI decision contexts, priority evaluation, training recommendations, and action execution remain structurally valid.", `AI clubs checked=${decisionChecks.length}`, "src/state/ai-decisions.ts", "evaluateClubPriorities"); else issue("HIGH", "AI decision integrity", "At least one AI decision context or recommendation was invalid.", `valid=${decisionChecks.filter(Boolean).length}/${decisionChecks.length}`, "src/state/ai-decisions.ts", "buildClubDecisionContext", "AI managers can write invalid tactical/training/financial decisions.", "Repair the invalid decision contract.", "Yes; decision output is deterministic.");
const replacementClub = Object.values(first.state.clubs).find((club) => club.aiManager)!;
const replacement = generateReplacementManager(first.state, replacementClub);
if (replacement && replacement.generation === (replacementClub.aiManager?.generation ?? 0) + 1 && replacement.id !== replacementClub.aiManager?.id) pass("Manager replacement lifecycle", "Replacement managers receive a new deterministic identity and incremented generation.", `old=${replacementClub.aiManager?.id}; new=${replacement.id}; generation=${replacement.generation}`, "src/state/ai-evolution.ts", "generateReplacementManager"); else issue("MEDIUM", "Manager replacement lifecycle", "Replacement manager identity or generation was invalid.", `old=${replacementClub.aiManager?.id}; new=${replacement?.id}; generation=${replacement?.generation}`, "src/state/ai-evolution.ts", "generateReplacementManager", "Manager churn can lose identity continuity.", "Repair replacement identity generation.", "Yes; manager identity is deterministic.");
const sameSeed = JSON.stringify(first.seasons) === JSON.stringify(second.seasons) && fingerprint(first.state) === fingerprint(second.state);
if (sameSeed) pass("Same-seed multi-season determinism", "Three bounded AI seasons produce identical manager, scheduler, decision, event, ledger, and squad state for the same seed.", `fingerprint length=${fingerprint(first.state).length}`, "scripts/step-6a-ai-world-manager-audit.ts", "runSeasons"); else issue("CRITICAL", "Same-seed multi-season determinism", "Same-seed AI state diverged.", "season or final fingerprints differed", "src/state/ai-actions.ts", "runAiActions", "AI saves are not reproducible.", "Block release and isolate nondeterministic AI input.", "Direct failure.");
const differentSeed = JSON.stringify(first.seasons) !== JSON.stringify(different.seasons) || fingerprint(first.state) !== fingerprint(different.state);
if (differentSeed) pass("Different-seed divergence", "Different seed diverges in bounded AI state where seeded manager/action inputs differ.", `same=${fingerprint(first.state).length}; different=${fingerprint(different.state).length}`, "scripts/step-6a-ai-world-manager-audit.ts", "runSeasons"); else issue("LOW", "Different-seed divergence", "Different seed did not diverge in bounded AI state.", "final fingerprints matched", "scripts/step-6a-ai-world-manager-audit.ts", "runSeasons", "Seed sensitivity was not demonstrated.", "Expand AI event/outcome coverage before treating this as RNG coverage.", "No direct corruption.");
add({ severity: "LOW", area: "Manager/job lifecycle", behavior: "Job offer generation and job acceptance are callable, but a bounded accepted-offer manager transition was not forced because offer selection is seeded and scenario-dependent.", evidence: "generateJobOffers and acceptJob exist; bounded run verified manager profiles and replacement generation, not a full accepted job-offer path.", file: "src/state/jobs.ts", functionName: "generateJobOffers", impact: "Full manager departure/appointment interaction remains partially unverified.", recommendation: "Use an existing accepted-offer fixture in a future focused audit.", determinism: "No change made." });

console.log("\nSEASON RESULTS");
for (const season of first.seasons) console.log(`${season.season}: days=${season.scheduledDays}; processed=${season.processedClubs}; managers=${season.managers}; negotiations=${season.negotiations}; transfers=${season.transfers}; invalid=${season.invalid}`);
console.log("\nSUMMARY");
for (const severity of ["CRITICAL", "HIGH", "MEDIUM", "LOW", "PASS"] as Severity[]) console.log(`${severity}: ${findings.filter((finding) => finding.severity === severity).length}`);
console.log("\nFINDINGS_JSON");
console.log(JSON.stringify(findings, null, 2));
