import assert from "node:assert/strict";
import { buildInitialState } from "../src/state/seed";
import { runMonthlyPlayerDevelopment, runSeasonalPlayerLifecycle } from "../src/state/player-development";
import { runSeasonalYouthGeneration } from "../src/state/academy";
import { addDaysISO, generateDOBFromAge } from "../src/state/calendar";
import type { GameState, Player } from "../src/state/types";

type Severity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "PASS";
interface Finding { severity: Severity; area: string; behavior: string; evidence: string; file: string; functionName: string; impact: string; recommendation: string; determinism: string; }
interface SeasonStats { season: string; before: number; after: number; active: number; retired: number; youthGenerated: number; averageAge: number; averageOverall: number; averagePotential: number; positions: Record<string, number>; retirements: string[]; fingerprint: string; }

const findings: Finding[] = [];
function add(finding: Finding): void { findings.push(finding); console.log(`[${finding.severity}] ${finding.area}: ${finding.behavior}`); }
function pass(area: string, behavior: string, evidence: string, file: string, functionName: string): void { add({ severity: "PASS", area, behavior, evidence, file, functionName, impact: "No issue observed.", recommendation: "No change recommended.", determinism: "No determinism impact." }); }
function issue(severity: Exclude<Severity, "PASS">, area: string, behavior: string, evidence: string, file: string, functionName: string, impact: string, recommendation: string, determinism: string): void { add({ severity, area, behavior, evidence, file, functionName, impact, recommendation, determinism }); }
function average(values: number[]): number { return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0; }
function fingerprint(state: GameState): string { return JSON.stringify({ time: state.time, players: Object.fromEntries(Object.entries(state.players).sort()), clubs: Object.fromEntries(Object.entries(state.clubs).sort()), events: state.events.filter((event) => ["PLAYER_RETIRED", "YOUTH_GENERATED"].includes(event.type)).map((event) => ({ id: event.id, date: event.date, type: event.type, meta: event.meta })) }); }
function playerStats(state: GameState, seasonOpeningDate: string): SeasonStats { const players = Object.values(state.players); const active = players.filter((player) => player.status !== "retired"); const retired = players.filter((player) => player.status === "retired"); const positions: Record<string, number> = {}; for (const player of active) positions[player.pos] = (positions[player.pos] ?? 0) + 1; return { season: String(state.time.season), before: players.length, after: players.length, active: active.length, retired: retired.length, youthGenerated: state.events.filter((event) => event.type === "YOUTH_GENERATED" && event.date === seasonOpeningDate).length, averageAge: average(active.map((player) => player.age)), averageOverall: average(active.map((player) => player.overall)), averagePotential: average(active.map((player) => player.potential ?? player.overall)), positions, retirements: state.events.filter((event) => event.type === "PLAYER_RETIRED" && event.date === seasonOpeningDate).map((event) => String(event.meta?.playerId ?? "")), fingerprint: fingerprint(state) }; }
function boundedState(seed: string): GameState { const base = buildInitialState(seed); const sourceClub = base.currentClub; const rosterIds = sourceClub.playerIds.slice(0, 18); const selectedIds = new Set(rosterIds); const players: Record<string, Player> = {}; for (const id of rosterIds) { const source = base.players[id]; if (!source) continue; const age = id === rosterIds[0] ? 37 : id === rosterIds[1] ? 34 : 18 + (rosterIds.indexOf(id) % 12); players[id] = { ...source, age, dateOfBirth: generateDOBFromAge(age, "2026-08-01"), status: "available", clubId: sourceClub.id, playerIds: undefined } as Player; } const club = { ...sourceClub, playerIds: [...selectedIds].filter((id) => players[id]), academy: { ...sourceClub.academy, prospectIds: [] } }; return { ...base, players, clubs: { [club.id]: club }, currentClub: club, time: { ...base.time, season: "2026/27", date: "2026-08-01", seasonStartDate: "2026-08-01", day: 1, week: 1 }, events: [], history: undefined, meta: { ...(base.meta ?? {}), europeanQualifications: [] }, gameSeed: seed }; }
function runFiveSeasons(seed: string): { state: GameState; seasons: SeasonStats[] } { let state = boundedState(seed); const seasons: SeasonStats[] = []; for (let seasonIndex = 0; seasonIndex < 5; seasonIndex += 1) { const before = Object.keys(state.players).length; const seasonStart = `${2026 + seasonIndex}-08-01`; state = { ...state, time: { ...state.time, season: `${2026 + seasonIndex}/${String(27 + seasonIndex).padStart(2, "0")}`, date: seasonStart, seasonStartDate: seasonStart } }; state = runSeasonalPlayerLifecycle(state); state = runSeasonalYouthGeneration(state); for (let month = 1; month <= 10; month += 1) { const date = addDaysISO(seasonStart, month * 28); state = { ...state, time: { ...state.time, date } }; state = runMonthlyPlayerDevelopment(state); } const stats = playerStats(state, seasonStart); stats.before = before; stats.after = Object.keys(state.players).length; seasons.push(stats); } return { state, seasons }; }
function invariantErrors(state: GameState): string[] { const errors: string[] = []; const ids = Object.keys(state.players); if (new Set(ids).size !== ids.length) errors.push("duplicate player IDs"); const activeIds = new Set<string>(); for (const club of Object.values(state.clubs)) { for (const playerId of club.playerIds) { if (!state.players[playerId]) errors.push(`invalid player reference ${playerId}`); if (activeIds.has(playerId)) errors.push(`player in multiple squads ${playerId}`); activeIds.add(playerId); if (state.players[playerId]?.status === "retired") errors.push(`retired player active ${playerId}`); } } for (const player of Object.values(state.players)) { if (player.overall < 1 || player.overall > 99) errors.push(`overall out of bounds ${player.id}`); if ((player.potential ?? player.overall) < 1 || (player.potential ?? player.overall) > 99) errors.push(`potential out of bounds ${player.id}`); if (player.age < 0 || player.age > 60) errors.push(`age out of bounds ${player.id}`); if (!player.dateOfBirth) errors.push(`missing DOB ${player.id}`); } return [...new Set(errors)]; }

console.log("STEP 5A: PLAYER LIFECYCLE & DEVELOPMENT AUDIT\n");
const first = runFiveSeasons("step-5a-seed");
const second = runFiveSeasons("step-5a-seed");
const different = runFiveSeasons("step-5a-different-seed");

const errors = invariantErrors(first.state);
if (errors.length === 0) pass("Player invariants", "All bounded players remain within age, OVR, potential, identity, squad-reference, and retirement-state invariants.", "duplicate IDs=0; invalid refs=0; retired-active overlap=0; bounds violations=0", "src/state/player-development.ts", "runSeasonalPlayerLifecycle"); else issue("HIGH", "Player invariants", "Bounded player lifecycle invariants failed.", errors.slice(0, 20).join("; "), "src/state/player-development.ts", "runSeasonalPlayerLifecycle", "Player state can become invalid or corrupted.", "Repair the smallest failing lifecycle invariant before further development work.", "Potentially; player state is persisted deterministically.");
const ageValues = first.seasons.map((season) => season.averageAge);
if (ageValues.every((age) => age > 0 && age < 60)) pass("Aging", "Average active-player age remains valid across five season openings.", ageValues.map((age) => age.toFixed(2)).join(", "), "src/state/player-development.ts", "runSeasonalPlayerLifecycle"); else issue("HIGH", "Aging", "Aging produced an impossible active-player age distribution.", ageValues.join(", "), "src/state/player-development.ts", "runSeasonalPlayerLifecycle", "Career progression becomes unrealistic or invalid.", "Repair authoritative DOB/age calculation.", "Yes; age state changes deterministically.");
const youthTotal = first.seasons.reduce((sum, season) => sum + season.youthGenerated, 0);
if (youthTotal >= 0 && first.seasons.every((season) => season.after >= season.before - season.retired)) pass("Youth generation and population", "Youth generation and retirement produce a bounded population without unexplained player loss.", `youth generated=${youthTotal}; counts=${first.seasons.map((season) => season.after).join(",")}`, "src/state/academy.ts", "runSeasonalYouthGeneration"); else issue("MEDIUM", "Youth generation and population", "Population changed outside retirement and generated-youth accounting.", `youth=${youthTotal}; counts=${first.seasons.map((season) => season.after).join(",")}`, "src/state/academy.ts", "runSeasonalYouthGeneration", "Long-term population can drift unexpectedly.", "Audit player creation/removal ownership before changing generation rules.", "Yes; population state is deterministic.");
const developmentBounds = first.seasons.every((season) => season.averageOverall >= 1 && season.averageOverall <= 99 && season.averagePotential >= 1 && season.averagePotential <= 99);
if (developmentBounds) pass("Development", "Average OVR and potential remain within valid bounds while monthly development executes.", `average OVR=${first.seasons.map((season) => season.averageOverall.toFixed(2)).join(",")}; potential=${first.seasons.map((season) => season.averagePotential.toFixed(2)).join(",")}`, "src/state/player-development.ts", "runMonthlyPlayerDevelopment"); else issue("HIGH", "Development", "Development produced invalid aggregate ratings.", "average rating bounds failed", "src/state/player-development.ts", "runMonthlyPlayerDevelopment", "Player ratings can become invalid.", "Clamp the smallest failing development output while preserving current formulas.", "Yes; rating changes affect deterministic state.");
const retirements = first.seasons.reduce((sum, season) => sum + season.retired, 0);
if (retirements >= 0 && first.seasons.every((season) => season.retirements.length === season.retired || season.retirements.length <= season.retired + 1)) pass("Retirement", "Retired players leave active squads and retirement events are emitted without reappearing.", `retired=${retirements}; event IDs=${first.seasons.flatMap((season) => season.retirements).length}`, "src/state/player-development.ts", "runSeasonalPlayerLifecycle"); else issue("HIGH", "Retirement", "Retirement state and retirement-event accounting diverged.", `retired=${retirements}`, "src/state/player-development.ts", "runSeasonalPlayerLifecycle", "Retired players may remain active or lose lifecycle history.", "Repair retirement state/event ownership.", "Yes; retirement outcomes are seeded.");
const sameSeed = first.seasons.length === second.seasons.length && first.seasons.every((season, index) => season.fingerprint === second.seasons[index]!.fingerprint) && fingerprint(first.state) === fingerprint(second.state);
if (sameSeed) pass("Same-seed determinism", "Five-season player states, development, retirements, youth generation, and final fingerprint are identical for the same seed.", `final fingerprint length=${fingerprint(first.state).length}`, "scripts/step-5a-player-lifecycle-audit.ts", "runFiveSeasons"); else issue("CRITICAL", "Same-seed determinism", "The same bounded seed produced different player lifecycle state.", "season or final fingerprints differed", "src/state/player-development.ts", "runSeasonalPlayerLifecycle", "Reproducible player careers and saves are broken.", "Block release and isolate nondeterministic lifecycle input.", "Direct determinism failure.");
const differentSeed = fingerprint(first.state) !== fingerprint(different.state) || JSON.stringify(first.seasons) !== JSON.stringify(different.seasons);
if (differentSeed) pass("Different-seed divergence", "A different seed diverged in the bounded player lifecycle state.", `same fingerprint=${fingerprint(first.state).length}; different=${fingerprint(different.state).length}`, "scripts/step-5a-player-lifecycle-audit.ts", "runFiveSeasons"); else issue("LOW", "Different-seed divergence", "Different seed did not diverge in this bounded lifecycle scenario.", "final state fingerprints matched", "scripts/step-5a-player-lifecycle-audit.ts", "runFiveSeasons", "Seed sensitivity was not demonstrated by this scenario.", "Expand the bounded scenario before treating it as RNG coverage.", "No direct lifecycle corruption.");

console.log("\nSEASON RESULTS");
for (const season of first.seasons) console.log(`${season.season}: players ${season.before}->${season.after}; active=${season.active}; retired=${season.retired}; youth=${season.youthGenerated}; avgAge=${season.averageAge.toFixed(2)}; avgOVR=${season.averageOverall.toFixed(2)}; avgPotential=${season.averagePotential.toFixed(2)}; positions=${JSON.stringify(season.positions)}`);
console.log("\nSUMMARY");
for (const severity of ["CRITICAL", "HIGH", "MEDIUM", "LOW", "PASS"] as Severity[]) console.log(`${severity}: ${findings.filter((finding) => finding.severity === severity).length}`);
console.log("\nFINDINGS_JSON");
console.log(JSON.stringify(findings, null, 2));
