import assert from "node:assert/strict";
import { buildInitialState } from "../src/state/seed";
import { recordPlayerLoan, runMonthlyPlayerDevelopment } from "../src/state/player-development";
import { completeTransferAtomically, verifyTransferConsistency } from "../src/state/transfer-hardening";
import { isFreeAgent } from "../src/state/transfer-rules";
import { acceptContractSession } from "../src/state/negotiation-sessions";
import type { Contract, GameState, Player } from "../src/state/types";

type Severity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "PASS";
interface Finding { severity: Severity; area: string; behavior: string; evidence: string; file: string; functionName: string; impact: string; recommendation: string; determinism: string; }
interface SeasonResult { season: string; transfer: string; loanRecords: number; duplicateLoanRecords: number; activePlayers: number; withoutClub: number; contractRows: number; fingerprint: string; }

const findings: Finding[] = [];
function add(finding: Finding): void { findings.push(finding); console.log(`[${finding.severity}] ${finding.area}: ${finding.behavior}`); }
function pass(area: string, behavior: string, evidence: string, file: string, functionName: string): void { add({ severity: "PASS", area, behavior, evidence, file, functionName, impact: "No issue observed.", recommendation: "No change recommended.", determinism: "No determinism impact." }); }
function issue(severity: Exclude<Severity, "PASS">, area: string, behavior: string, evidence: string, file: string, functionName: string, impact: string, recommendation: string, determinism: string): void { add({ severity, area, behavior, evidence, file, functionName, impact, recommendation, determinism }); }
function duplicate(values: string[]): string[] { const seen = new Set<string>(); const result = new Set<string>(); for (const value of values) { if (seen.has(value)) result.add(value); seen.add(value); } return [...result]; }
function fingerprint(state: GameState): string { return JSON.stringify({ time: state.time, players: Object.fromEntries(Object.entries(state.players).sort()), clubs: Object.fromEntries(Object.entries(state.clubs).sort()), contracts: state.contracts, events: state.events.filter((event) => ["TRANSFER_COMPLETED", "PLAYER_MOVEMENT", "PLAYER_RETIRED"].includes(event.type)).map((event) => ({ id: event.id, date: event.date, type: event.type, meta: event.meta })) }); }
function compactState(seed: string): GameState { const base = buildInitialState(seed); const seller = base.currentClub; const buyer = Object.values(base.clubs).find((club) => club.id !== seller.id && club.playerIds.length > 0); assert(buyer, "buyer unavailable"); const selected = seller.playerIds.slice(0, 4); const players: Record<string, Player> = {}; for (const playerId of selected) { const player = base.players[playerId]; if (player) players[playerId] = { ...player, clubId: seller.id, status: "available" }; } const sellerClub = { ...seller, playerIds: Object.keys(players) }; const buyerClub = { ...buyer, playerIds: [] }; const contracts: Contract[] = Object.keys(players).map((playerId) => ({ playerId, clubId: seller.id, status: "active" })); return { ...base, players, clubs: { [seller.id]: sellerClub, [buyerClub.id]: buyerClub }, currentClub: sellerClub, contracts, transfers: [], negotiations: [], events: [], fixtures: [], time: { ...base.time, season: "2026/27", date: "2026-08-01", seasonStartDate: "2026-08-01" }, gameSeed: seed }; }
function invariantErrors(state: GameState): string[] { const errors: string[] = []; const rostered = new Set<string>(); for (const club of Object.values(state.clubs)) for (const playerId of club.playerIds) { if (!state.players[playerId]) errors.push(`invalid player ${playerId}`); if (rostered.has(playerId)) errors.push(`multiple squads ${playerId}`); rostered.add(playerId); if (state.players[playerId]?.status === "retired") errors.push(`retired active ${playerId}`); } for (const player of Object.values(state.players)) if (player.clubId && !state.clubs[player.clubId]) errors.push(`invalid club ${player.clubId}`); const contractKeys = (state.contracts ?? []).map((contract) => contract.playerId); errors.push(...duplicate(contractKeys).map((key) => `duplicate contract ${key}`)); for (const player of Object.values(state.players)) if (!player.clubId) errors.push(`orphan player ${player.id}`); return [...new Set(errors)]; }
function runThreeSeasons(seed: string): { state: GameState; seasons: SeasonResult[] } { let state = compactState(seed); const seasons: SeasonResult[] = []; const clubIds = Object.keys(state.clubs); const sellerId = clubIds[0]!; const buyerId = clubIds[1]!; for (let index = 0; index < 3; index += 1) { const season = `${2026 + index}/${String(27 + index).padStart(2, "0")}`; const date = `${2026 + index}-08-01`; state = { ...state, time: { ...state.time, season, date, seasonStartDate: date } }; const candidate = Object.values(state.players).find((player) => player.clubId === sellerId && state.clubs[sellerId]!.playerIds.includes(player.id)); assert(candidate, "season transfer candidate unavailable"); const transfer = completeTransferAtomically(state, candidate.id, sellerId, buyerId); assert(transfer.success, `transfer failed: ${transfer.reason}`); state = transfer.state; const consistency = verifyTransferConsistency(state, candidate.id, buyerId); if (!consistency.consistent) issue("HIGH", "Transfer + contract consistency", "Transfer and contract ownership diverged.", consistency.violations.join("; "), "src/state/transfer-hardening.ts", "completeTransferAtomically", "A moved player can retain stale contract ownership.", "Repair atomic transfer ownership.", "Yes."); const loanTarget = Object.values(state.players).find((player) => player.id !== candidate.id); if (loanTarget) { state = recordPlayerLoan(state, loanTarget.id, buyerId, date, `${2027 + index}-06-30`); state = recordPlayerLoan(state, loanTarget.id, buyerId, date, `${2027 + index}-06-30`); } state = { ...state, time: { ...state.time, date: `${2026 + index}-11-01` } }; state = runMonthlyPlayerDevelopment(state); const loanKeys = Object.values(state.players).flatMap((player) => (player.loanHistory ?? []).map((loan) => `${player.id}:${loan.id}`)); const duplicateLoanRecords = duplicate(loanKeys).length; const withoutClub = Object.values(state.players).filter((player) => !player.clubId || !state.clubs[player.clubId]).length; seasons.push({ season, transfer: candidate.id, loanRecords: loanKeys.length, duplicateLoanRecords, activePlayers: Object.values(state.players).filter((player) => player.status !== "retired").length, withoutClub, contractRows: state.contracts.length, fingerprint: fingerprint(state) }); } return { state, seasons }; }

console.log("STEP 5C: LOANS, CONTRACT LIFECYCLE & PLAYER MOVEMENT AUDIT\n");
const first = runThreeSeasons("step-5c-seed");
const second = runThreeSeasons("step-5c-seed");
const different = runThreeSeasons("step-5c-different-seed");
const invariantViolations = invariantErrors(first.state);
if (invariantViolations.length === 0) pass("Movement invariants", "Three-season movement preserves valid clubs, unique squads, contract uniqueness, and non-orphaned players.", "duplicate IDs=0; multiple squads=0; invalid clubs=0; retired-active=0; duplicate contracts=0; orphans=0", "src/state/transfer-hardening.ts", "completeTransferAtomically"); else issue("HIGH", "Movement invariants", "Movement lifecycle invariants failed.", invariantViolations.join("; "), "src/state/transfer-hardening.ts", "completeTransferAtomically", "Player movement state is inconsistent.", "Repair the smallest failing movement invariant.", "Yes.");
const duplicateLoans = first.seasons.reduce((sum, season) => sum + season.duplicateLoanRecords, 0);
if (duplicateLoans === 0) pass("Loan record uniqueness", "Repeated loan creation does not duplicate logical loan records.", "duplicate loan records=0", "src/state/player-development.ts", "recordPlayerLoan"); else issue("MEDIUM", "Loan record uniqueness", "Repeating the same loan operation creates duplicate loan history records.", `duplicate loan records=${duplicateLoans}`, "src/state/player-development.ts", "recordPlayerLoan", "Loan history can multiply under repeated lifecycle processing.", "Deduplicate loanHistory by its deterministic loan ID.", "Yes; history state changes.");
const transferConsistency = first.seasons.every((season) => season.contractRows > 0 && season.withoutClub === 0);
if (transferConsistency) pass("Transfer and contract ownership", "Transferred players retain valid destination ownership and contract rows across three seasons.", first.seasons.map((season) => `${season.season}:contracts=${season.contractRows}`).join(", "), "src/state/transfer-hardening.ts", "completeTransferAtomically"); else issue("HIGH", "Transfer and contract ownership", "A moved player lost valid ownership or contract state.", JSON.stringify(first.seasons), "src/state/transfer-hardening.ts", "completeTransferAtomically", "Player identity and contract ownership diverge.", "Repair the atomic ownership update.", "Yes.");
add({ severity: "LOW", area: "Loan squad movement and return", behavior: "A complete temporary-club loan and return lifecycle is not exposed by the audited production APIs.", evidence: "recordPlayerLoan appends loanHistory but does not update club.playerIds, temporary ownership, or provide a return operation.", file: "src/state/player-development.ts", functionName: "recordPlayerLoan", impact: "Loan membership, development at the temporary club, and return cannot be verified without inventing behavior.", recommendation: "Keep this lifecycle explicitly unverified until an authoritative loan operation exists.", determinism: "No change made." });
add({ severity: "LOW", area: "Contract expiry and termination", behavior: "No authoritative expiry, release, or contract-termination operation was found in the audited state APIs.", evidence: "Contract status supports active/expiring/negotiating/released, but no lifecycle function was available to perform expiry or release and update squad ownership.", file: "src/state/types.ts", functionName: "Contract", impact: "Expiry, renewal completion, release, and expired-player transfer behavior remain unverified.", recommendation: "Audit these paths when an authoritative contract lifecycle operation exists.", determinism: "No change made." });
const sameSeed = JSON.stringify(first.seasons) === JSON.stringify(second.seasons) && fingerprint(first.state) === fingerprint(second.state);
if (sameSeed) pass("Same-seed determinism", "Three-season movement, loan-history, contract, and player states are identical for the same seed.", `final fingerprint length=${fingerprint(first.state).length}`, "scripts/step-5c-loans-contract-lifecycle-audit.ts", "runThreeSeasons"); else issue("CRITICAL", "Same-seed determinism", "Same-seed movement lifecycle diverged.", "season or final fingerprints differed", "src/state/transfer-hardening.ts", "completeTransferAtomically", "Reproducible player movement is broken.", "Block release and isolate nondeterminism.", "Direct failure.");
const differentSeed = JSON.stringify(first.seasons) !== JSON.stringify(different.seasons) || fingerprint(first.state) !== fingerprint(different.state);
if (differentSeed) pass("Different-seed divergence", "The different seed diverged in the bounded movement state.", `same=${fingerprint(first.state).length}; different=${fingerprint(different.state).length}`, "scripts/step-5c-loans-contract-lifecycle-audit.ts", "runThreeSeasons"); else issue("LOW", "Different-seed divergence", "Different seed did not diverge in this bounded movement scenario.", "final fingerprints matched", "scripts/step-5c-loans-contract-lifecycle-audit.ts", "runThreeSeasons", "Seed sensitivity was not demonstrated.", "Expand outcome coverage before treating this as RNG coverage.", "No direct corruption.");

console.log("\nSEASON RESULTS");
for (const season of first.seasons) console.log(`${season.season}: transfer=${season.transfer}; loans=${season.loanRecords}; duplicateLoans=${season.duplicateLoanRecords}; active=${season.activePlayers}; withoutClub=${season.withoutClub}; contracts=${season.contractRows}`);
console.log("\nSUMMARY");
for (const severity of ["CRITICAL", "HIGH", "MEDIUM", "LOW", "PASS"] as Severity[]) console.log(`${severity}: ${findings.filter((finding) => finding.severity === severity).length}`);
console.log("\nFINDINGS_JSON");
console.log(JSON.stringify(findings, null, 2));
