/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as BoardRouteImport } from './routes/board'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FansRouteImport } from './routes/fans'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as FixturesModernRouteImport } from './routes/fixtures-modern'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LeaguePyramidRouteImport } from './routes/league-pyramid'
import { Route as ManagerProfileRouteImport } from './routes/manager-profile'
import { Route as MatchRouteImport } from './routes/match'
import { Route as NegotiationsRouteImport } from './routes/negotiations'
import { Route as NewCareerRouteImport } from './routes/new-career'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as ScoutingRouteImport } from './routes/scouting'
import { Route as SeasonReportRouteImport } from './routes/season-report'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as StadiumRouteImport } from './routes/stadium'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as TacticsRouteImport } from './routes/tactics'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as TreatmentRouteImport } from './routes/treatment'
import { Route as PlayerPlayerIdRouteImport } from './routes/player.$playerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FansRoute = FansRouteImport.update({
  id: '/fans',
  path: '/fans',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesModernRoute = FixturesModernRouteImport.update({
  id: '/fixtures-modern',
  path: '/fixtures-modern',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguePyramidRoute = LeaguePyramidRouteImport.update({
  id: '/league-pyramid',
  path: '/league-pyramid',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerProfileRoute = ManagerProfileRouteImport.update({
  id: '/manager-profile',
  path: '/manager-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const NegotiationsRoute = NegotiationsRouteImport.update({
  id: '/negotiations',
  path: '/negotiations',
  getParentRoute: () => rootRouteImport,
} as any)
const NewCareerRoute = NewCareerRouteImport.update({
  id: '/new-career',
  path: '/new-career',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutingRoute = ScoutingRouteImport.update({
  id: '/scouting',
  path: '/scouting',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonReportRoute = SeasonReportRouteImport.update({
  id: '/season-report',
  path: '/season-report',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const StadiumRoute = StadiumRouteImport.update({
  id: '/stadium',
  path: '/stadium',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TacticsRoute = TacticsRouteImport.update({
  id: '/tactics',
  path: '/tactics',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentRoute = TreatmentRouteImport.update({
  id: '/treatment',
  path: '/treatment',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlayerIdRoute = PlayerPlayerIdRouteImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/fans': typeof FansRoute
  '/fixtures': typeof FixturesRoute
  '/fixtures-modern': typeof FixturesModernRoute
  '/inbox': typeof InboxRoute
  '/league-pyramid': typeof LeaguePyramidRoute
  '/manager-profile': typeof ManagerProfileRoute
  '/match': typeof MatchRoute
  '/negotiations': typeof NegotiationsRoute
  '/new-career': typeof NewCareerRoute
  '/office': typeof OfficeRoute
  '/scouting': typeof ScoutingRoute
  '/season-report': typeof SeasonReportRoute
  '/squad': typeof SquadRoute
  '/stadium': typeof StadiumRoute
  '/staff': typeof StaffRoute
  '/tactics': typeof TacticsRoute
  '/training': typeof TrainingRoute
  '/transfers': typeof TransfersRoute
  '/treatment': typeof TreatmentRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/fans': typeof FansRoute
  '/fixtures': typeof FixturesRoute
  '/fixtures-modern': typeof FixturesModernRoute
  '/inbox': typeof InboxRoute
  '/league-pyramid': typeof LeaguePyramidRoute
  '/manager-profile': typeof ManagerProfileRoute
  '/match': typeof MatchRoute
  '/negotiations': typeof NegotiationsRoute
  '/new-career': typeof NewCareerRoute
  '/office': typeof OfficeRoute
  '/scouting': typeof ScoutingRoute
  '/season-report': typeof SeasonReportRoute
  '/squad': typeof SquadRoute
  '/stadium': typeof StadiumRoute
  '/staff': typeof StaffRoute
  '/tactics': typeof TacticsRoute
  '/training': typeof TrainingRoute
  '/transfers': typeof TransfersRoute
  '/treatment': typeof TreatmentRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/fans': typeof FansRoute
  '/fixtures': typeof FixturesRoute
  '/fixtures-modern': typeof FixturesModernRoute
  '/inbox': typeof InboxRoute
  '/league-pyramid': typeof LeaguePyramidRoute
  '/manager-profile': typeof ManagerProfileRoute
  '/match': typeof MatchRoute
  '/negotiations': typeof NegotiationsRoute
  '/new-career': typeof NewCareerRoute
  '/office': typeof OfficeRoute
  '/scouting': typeof ScoutingRoute
  '/season-report': typeof SeasonReportRoute
  '/squad': typeof SquadRoute
  '/stadium': typeof StadiumRoute
  '/staff': typeof StaffRoute
  '/tactics': typeof TacticsRoute
  '/training': typeof TrainingRoute
  '/transfers': typeof TransfersRoute
  '/treatment': typeof TreatmentRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/board'
    | '/calendar'
    | '/fans'
    | '/fixtures'
    | '/fixtures-modern'
    | '/inbox'
    | '/league-pyramid'
    | '/manager-profile'
    | '/match'
    | '/negotiations'
    | '/new-career'
    | '/office'
    | '/scouting'
    | '/season-report'
    | '/squad'
    | '/stadium'
    | '/staff'
    | '/tactics'
    | '/training'
    | '/transfers'
    | '/treatment'
    | '/player/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/board'
    | '/calendar'
    | '/fans'
    | '/fixtures'
    | '/fixtures-modern'
    | '/inbox'
    | '/league-pyramid'
    | '/manager-profile'
    | '/match'
    | '/negotiations'
    | '/new-career'
    | '/office'
    | '/scouting'
    | '/season-report'
    | '/squad'
    | '/stadium'
    | '/staff'
    | '/tactics'
    | '/training'
    | '/transfers'
    | '/treatment'
    | '/player/$playerId'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/board'
    | '/calendar'
    | '/fans'
    | '/fixtures'
    | '/fixtures-modern'
    | '/inbox'
    | '/league-pyramid'
    | '/manager-profile'
    | '/match'
    | '/negotiations'
    | '/new-career'
    | '/office'
    | '/scouting'
    | '/season-report'
    | '/squad'
    | '/stadium'
    | '/staff'
    | '/tactics'
    | '/training'
    | '/transfers'
    | '/treatment'
    | '/player/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  BoardRoute: typeof BoardRoute
  CalendarRoute: typeof CalendarRoute
  FansRoute: typeof FansRoute
  FixturesRoute: typeof FixturesRoute
  FixturesModernRoute: typeof FixturesModernRoute
  InboxRoute: typeof InboxRoute
  LeaguePyramidRoute: typeof LeaguePyramidRoute
  ManagerProfileRoute: typeof ManagerProfileRoute
  MatchRoute: typeof MatchRoute
  NegotiationsRoute: typeof NegotiationsRoute
  NewCareerRoute: typeof NewCareerRoute
  OfficeRoute: typeof OfficeRoute
  ScoutingRoute: typeof ScoutingRoute
  SeasonReportRoute: typeof SeasonReportRoute
  SquadRoute: typeof SquadRoute
  StadiumRoute: typeof StadiumRoute
  StaffRoute: typeof StaffRoute
  TacticsRoute: typeof TacticsRoute
  TrainingRoute: typeof TrainingRoute
  TransfersRoute: typeof TransfersRoute
  TreatmentRoute: typeof TreatmentRoute
  PlayerPlayerIdRoute: typeof PlayerPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fans': {
      id: '/fans'
      path: '/fans'
      fullPath: '/fans'
      preLoaderRoute: typeof FansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures-modern': {
      id: '/fixtures-modern'
      path: '/fixtures-modern'
      fullPath: '/fixtures-modern'
      preLoaderRoute: typeof FixturesModernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league-pyramid': {
      id: '/league-pyramid'
      path: '/league-pyramid'
      fullPath: '/league-pyramid'
      preLoaderRoute: typeof LeaguePyramidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-profile': {
      id: '/manager-profile'
      path: '/manager-profile'
      fullPath: '/manager-profile'
      preLoaderRoute: typeof ManagerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negotiations': {
      id: '/negotiations'
      path: '/negotiations'
      fullPath: '/negotiations'
      preLoaderRoute: typeof NegotiationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-career': {
      id: '/new-career'
      path: '/new-career'
      fullPath: '/new-career'
      preLoaderRoute: typeof NewCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouting': {
      id: '/scouting'
      path: '/scouting'
      fullPath: '/scouting'
      preLoaderRoute: typeof ScoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season-report': {
      id: '/season-report'
      path: '/season-report'
      fullPath: '/season-report'
      preLoaderRoute: typeof SeasonReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stadium': {
      id: '/stadium'
      path: '/stadium'
      fullPath: '/stadium'
      preLoaderRoute: typeof StadiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactics': {
      id: '/tactics'
      path: '/tactics'
      fullPath: '/tactics'
      preLoaderRoute: typeof TacticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatment': {
      id: '/treatment'
      path: '/treatment'
      fullPath: '/treatment'
      preLoaderRoute: typeof TreatmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$playerId': {
      id: '/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/player/$playerId'
      preLoaderRoute: typeof PlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  BoardRoute: BoardRoute,
  CalendarRoute: CalendarRoute,
  FansRoute: FansRoute,
  FixturesRoute: FixturesRoute,
  FixturesModernRoute: FixturesModernRoute,
  InboxRoute: InboxRoute,
  LeaguePyramidRoute: LeaguePyramidRoute,
  ManagerProfileRoute: ManagerProfileRoute,
  MatchRoute: MatchRoute,
  NegotiationsRoute: NegotiationsRoute,
  NewCareerRoute: NewCareerRoute,
  OfficeRoute: OfficeRoute,
  ScoutingRoute: ScoutingRoute,
  SeasonReportRoute: SeasonReportRoute,
  SquadRoute: SquadRoute,
  StadiumRoute: StadiumRoute,
  StaffRoute: StaffRoute,
  TacticsRoute: TacticsRoute,
  TrainingRoute: TrainingRoute,
  TransfersRoute: TransfersRoute,
  TreatmentRoute: TreatmentRoute,
  PlayerPlayerIdRoute: PlayerPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
